### ISSUE TITLE
Server error 500 - migrations not applied

### ISSUE THREAD

**Issue by ciur** [linuxserver/docker-papermerge#6]
Hi,

I am author of upstream application (i.e. Papermerge).
A guy [reported following bug](https://github.com/ciur/papermerge/issues/134).
In his bug report I see that migrations were not applied. However I see that [your docker image does run migrations](https://github.com/linuxserver/docker-papermerge/blob/master/root/etc/cont-init.d/50-config#L19).
Again, from same report I learn that both worker and main app do not have any database table available.

That guy runs Windows 10 + [this thing](https://rancher.com/).

Maybe you can help with some insights, because I am totally disarmed as I neither have Windows available nor do I use kubernetes/Rancher.

Thank you very much for providing a fantastic docker image for papermerge!

**Comment by DaveNadeau** [comment]
I'm the guy that reported this issue.  Please let me know if you have any additional questions.  attached is the log file from the papermerge container via Rancher.
[container.log](https://github.com/linuxserver/docker-papermerge/files/5280401/container.log)

**Comment by alex-phillips** [comment]
@DaveNadeau Thanks for the report. Your container log doesn't have all of the information to help debug, it looks like it's only a segment at the end of the output. Can you provide the logs starting from the beginning? To ensure you have the correct information, you should see the following at the top o the logs:

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------
```

You may need to restart the container or remove and recreate the container to get the logs at the initial runtime.

**Comment by DaveNadeau** [comment]
@alex-phillips below are the attached logs (verified text image at top of file).  Please let me know what else you might need as my wife and I are very excited to start using this system.  

I should note that I am Using Rancher as a k8s management system.  the server this image lives on is linux(ubuntu 20.04), but I use the web interface on my win10 laptop to interface.  Thanks for your time!
[container (1).log](https://github.com/linuxserver/docker-papermerge/files/5285620/container.1.log)

**Comment by alex-phillips** [comment]
@DaveNadeau This line in the logs is probably the issue:

```
sqlite3.OperationalError: database is locked
```

The system is attempting to run the migrations but fails due to the database being locked. As it fails and then proceeds with the software, the migrations were never run so the database isn't set up properly. Since you're using sqlite3, I'm not sure what could cause the database to be locked other than another container using it. Permissions could also be an issue here.

**Comment by aptalca** [comment]
If the config folder is on a remote share, that would be why. Sqlite needs to be on a local filesystem.

I don't know the details but since windows is mentioned, I'm going to assume that the config folder is on windows's main ntfs volume and it is shared with the Linux container, which is causing the issue.

On windows, even docker highly recommends using WSL2 and storing linux containers' persistent (mapped) data inside the Linux apps' filesystems rather than the windows filesystem to avoid such issues.

**Comment by DaveNadeau** [comment]
Thank you @aptalca and @alex-phillips, yes I was trying to put the config folder on the local drive and the database on my samba-shared RAID 10 drive (I wanted the config files local to the guest VM that I'm running Docker on, but the data in my shared drive).  I have moved the database to the local drive and all is working now.  Thanks for your time.  Please mark as resolved.
